unit Anon.Generators.CompanyName;

interface

uses
  SysUtils, Anon.Interfaces, Demo.Core.ServiceLocator, Demo.Core.Rtti;

type
  [Alias('CompanyName')]
  TCompanyNameGenerator = class(TInterfacedObject, IGenerator)
  public
    function GenerateValue: Variant;
    procedure SetParams(const Params: System.TArray<System.string>);
  end;

implementation

{$region 'Random data for company names'}

const
  CompanyNames: array [0..196] of string = (
    'A.D. Vision',
    'Academia.edu',
    'Accoona',
    'ADV Films',
    'Albemarle Corporation',
    'Alderac Entertainment Group',
    'Alexa',
    'All Media Network',
    'All-Clad',
    'Allen-Bradley',
    'Alternative Addiction',
    'American Express',
    'American Nitrox Divers',
    'Amway',
    'Andreessen Horowitz',
    'AOL',
    'AquaBounty Technologies',
    'Avis Rent a Car System',
    'Babcock & Wilcox',
    'Barnes & Noble',
    'Beatport',
    'Bechtel',
    'Bell & Howell',
    'Benchmark ',
    'Berkshire Hathaway',
    'Berlitz School of Languages',
    'BgC3',
    'Black & Decker',
    'Blockbuster ',
    'Bloomberg ',
    'Boston Scientific',
    'Branded Entertainment Network',
    'BrightSource Energy',
    'Budget Autonoleggio',
    'Carlson Rezidor Hotel Group',
    'Carrier Corporation',
    'Case IH',
    'Caterpillar ',
    'Cedar Fair Entertainment Company',
    'Celera Genomics',
    'Celestron',
    'CenturyLink',
    'Christie''s',
    'Cloudera',
    'CME Group',
    'Cobalt International Energy',
    'Coinbase',
    'Commvault',
    'Complesso militare-industriale e politico',
    'ComScore',
    'Corning Incorporated',
    'Coty ',
    'Crystal Dynamics',
    'Cummins',
    'David Yurman',
    'DC Direct',
    'Decipher ',
    'DeWalt',
    'DigitalGlobe',
    'DigiTech',
    'DoubleClick',
    'Dremel',
    'Dye Precision',
    'Dynetics',
    'EMachines',
    'Energy Future Holdings Corporation',
    'Enron',
    'Esri',
    'Evinrude Outboard Motors',
    'Fandor',
    'Fannie Mae',
    'Fantasy Flight Games',
    'Fantasy Games Unlimited',
    'Faraday Future',
    'Federal Deposit Insurance Corporation',
    'FireEye',
    'First Solar',
    'Fitch Ratings',
    'Fortune Brands',
    'Fox Film Corporation',
    'Freddie Mac',
    'Freeport-McMoRan',
    'Funimation',
    'Garrett Systems',
    'GE Oil & Gas',
    'General Dynamics Electric Boat',
    'Genesys',
    'Glassdoor',
    'Glastron',
    'Global Infrastructure Partners',
    'GMT Games',
    'Gold''s Gym',
    'Golden Apple Comics',
    'Gruppo NASDAQ OMX',
    'Hal Roach Studios',
    'Harman International Industries',
    'Template Harman International Industries',
    'Hearst Corporation',
    'Hearst Haggin Tevis',
    'Hines Interests Limited Partnership',
    'Hooters',
    'Hortonworks',
    'Icewarp',
    'ICM Registry',
    'Incyte',
    'Index Ventures',
    'Indiegogo',
    'IntercontinentalExchange',
    'Intouch Solutions',
    'Ion Storm',
    'Iron Crown Enterprises',
    'Irrational Games',
    'Jamba Juice',
    'Jim Beam',
    'Jim Henson Productions',
    'Joseff of Hollywood',
    'Joy Global',
    'Judges Guild',
    'Kaltura',
    'Keurig Green Mountain',
    'Kickstarter',
    'Kijiji',
    'LendEDU',
    'Lion Rampant',
    'Loctite',
    'Looking Glass Studios',
    'Loudwire',
    'Lux Capital',
    'Lycos',
    'Lyft',
    'Maker''s Mark',
    'Manatt Phelps & Phillips',
    'MapQuest',
    'Marriott International',
    'Mazor Robotics',
    'Meade Instruments Corporation',
    'Mercury Marine',
    'Meru Networks',
    'Metagaming Concepts',
    'MGM Resorts International',
    'Milton Bradley Company',
    'Mole-Richardson',
    'Moody''s',
    'Morgans Hotel Group',
    'MPEG LA',
    'Namecheap',
    'Nanosys',
    'Navistar International',
    'The Nerd Machine',
    'Netflix',
    'Network Solutions',
    'New Jersey Transit',
    'NexTag',
    'Nielsen Media Research',
    'Nuance Communications',
    'Nutmeg',
    'NYC Media Group',
    'Occidental Petroleum',
    'Ocean Spray',
    'OpenTable',
    'Otis Elevator Company',
    'Palladium Books',
    'Park Plaza Hotels & Resorts',
    'Parker Brothers',
    'PayScale',
    'Pembient',
    'Pentacon',
    'Pentaho',
    'Pinkerton National Detective Agency',
    'Planet Hollywood',
    'Polaris Industries',
    'POW Entertainment',
    'Puppet Heap',
    'Qlik',
    'Radio Corporation of America',
    'Radisson Hotels',
    'RAND Corporation',
    'Rio Grande Games',
    'RRE Ventures',
    'Safeway',
    'Salesforce.com',
    'Samsonite ',
    'SBE Entertainment Group',
    'Scarab ',
    'Schlumberger',
    'SeaWorld Parks & Entertainment',
    'Sequoia Capital',
    'Shake Shack',
    'Shapeways',
    'Shout! Factory',
    'Singer ',
    'Singularity University',
    'Society of the Plastics Industry',
    'Sotheby''s',
    'Space Adventures',
    'Spaceflight Industries',
    'Square Inc.'
);

{$endregion}

{ TCompanyNameGenerator }

function TCompanyNameGenerator.GenerateValue: Variant;
var
  Index: Integer;
begin
  Index := Random(Length(CompanyNames));
  Result := CompanyNames[Index];
end;

procedure TCompanyNameGenerator.SetParams(
  const Params: System.TArray<System.string>);
begin

end;

initialization
  ServiceLocator.RegisterClass(TCompanyNameGenerator);

end.
